/*
 * Brief: Web pages implementation.
 * author: Thomas Georgiadis
 * TODO : Upgrade the web logic to support CSS + JS for better pages.
 */
#include <stdio.h>
#include "tc74.h"
#include "dht22.h"
#include "sntp_client.h"
#include "ldr.h"
#include "MQ135.h"
#include "sen0193.h"

void instant_status(char *html_code)
{
  float dht22Temperature = 0.0;
  float dht22Humidity = 0.0;
  readDHT(&dht22Humidity, &dht22Temperature);
  sprintf(html_code, "<!DOCTYPE html>\n"
			"<html lang=\"en\">\n"
			"  <head>\n"
			"    <meta charset=\"UTF-8\" />\n"
			"    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n"
			"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
			"    <link\n"
			"      href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap\"\n"
			"      rel=\"stylesheet\"\n"
			"    />\n"
			"    <title>Plant Monitor</title>\n"
			"    <style>\n"
			"      * {\n"
			"        margin: 0;\n"
			"        padding: 0;\n"
			"        box-sizing: border-box;\n"
			"      }\n"
			"      body {\n"
			"        font-family: \"Inter\", sans-serif;\n"
			"        color: #343a40;\n"
			"        line-height: 1;\n"
			"        display: flex;\n"
			"        justify-content: center;\n"
			"      }\n"
			"\n"
			"      table {\n"
			"        width: 650px;\n"
			"        margin-top: 100px;\n"
			"        font-size: 18px;\n"
			"        border-collapse: collapse;\n"
			"      }\n"
			"      td,\n"
			"      th {\n"
			"        padding: 16px 24px;\n"
			"        text-align: left;\n"
			"      }\n"
			"\n"
			"      thead th {\n"
			"        background-color: #087f5b;\n"
			"        color: white;\n"
			"        width: 25%%;\n"
			"      }\n"
			"\n"
			"      tbody tr:nth-child(odd) {\n"
			"        background-color: #f8f9fa;\n"
			"      }\n"
			"      tbody tr:nth-child(even) {\n"
			"        background-color: #e9ecef;\n"
			"      }\n"
			"    </style>\n"
                        "  </head>\n"
                        "  <body>\n"
                        "    <table>\n"
                        "      <thead>\n"
                        "        <tr>\n"
                        "          <th>Plant Sensors</th>\n"
                        "          <th>Value (SI)</th>\n"
                        "        </tr>\n"
                        "      </thead>\n"
                        "      <tbody>\n"
                        "        <tr>\n"
                        "          <th>Τimestamp</th>\n"
                        "          <td>%s</td>\n"
                        "        </tr>\n"
                        "        <tr>\n"
                        "          <th>TC74 Temperature</th>\n"
                        "          <td>%d C°</td>\n"
                        "        </tr>\n"
                        "        <tr>\n"
                        "          <th>DHT22 Temperature</th>\n"
                        "          <td>%f C°</td>\n"
                        "        </tr>\n"
                        "        <tr>\n"
                        "          <th>DHT22 Humidity</th>\n"
                        "          <td>%f %%</td>\n"
                        "        </tr>\n"
                        "        <tr>\n"
                        "          <th>MQ135 CO2 Level</th>\n"
                        "          <td>%f PPM</td>\n"
                        "        </tr>\n"
                        "        <tr>\n"
                        "          <th>LDR Light intensity</th>\n"
                        "          <td>%d%%</td>\n"
                        "        </tr>\n"
                        "        <tr>\n"
                        "          <th>Soil moisture</th>\n"
                        "          <td>%d%%</td>\n"
                        "        </tr>\n"
                        "      </tbody>\n"
                        "    </table>\n"
                        "  </body>\n"
                        "</html>", get_timestamp(),temperature_reading(),dht22Temperature,dht22Humidity,get_co2_ppm_value(),		       	get_light_intensity(),get_soil_humidity());
}
